export enum Icon {
  ArrowDownLeft = 'ph_arrow-down-left-light',
  ArrowDown = 'ph_arrow-down-light',
  ArrowDownRight = 'ph_arrow-down-right-light',
  ArrowLeft = 'ph_arrow-left-light',
  ArrowRight = 'ph_arrow-right-light',
  ArrowUpLeft = 'ph_arrow-up-left-light',
  ArrowUp = 'ph_arrow-up-light',
  ArrowUpRight = 'ph_arrow-up-right-light',
  Behance = 'ph_behance-logo-light',
  Check = 'ph_check-light',
  Dribbble = 'ph_dribbble-logo-light',
  EnvelopeSimple = 'ph_envelope-simple-light',
  Facebook = 'ph_facebook-logo-light',
  Info = 'ph_info-light',
  Instagram = 'ph_instagram-logo-light',
  Link = 'ph_link-light',
  Phone = 'ph_phone-light',
  Pinterest = 'ph_pinterest-logo-light',
  Plus = 'ph_plus-light',
  Tiktok = 'ph_tiktok-logo-light',
  Twitch = 'ph_twitch-logo-light',
  Twitter = 'ph_twitter-logo-light',
  Whatsapp = 'ph_whatsapp-logo-light',
  Youtube = 'ph_youtube-logo-light',
  Vector = 'Vector',
}
